# Generated by Django 3.2.9 on 2021-12-10 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasePageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceCourseLable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.CharField(max_length=256, null=True, verbose_name='день курса')),
                ('title_exercise_extra', models.CharField(blank='True', max_length=256, verbose_name='Екста Задание: название')),
                ('exercise_extra', models.TextField(blank='True', null=True, verbose_name='задачи "экстразадания"')),
                ('title_exercise_1', models.CharField(blank='True', max_length=256, verbose_name='Первое задание: название')),
                ('exercise_1', models.TextField(blank='True', null=True, verbose_name='Первое задание: задачи')),
                ('title_exercise_2', models.CharField(blank='True', max_length=256, verbose_name='Второе задание: название')),
                ('exercise_2', models.TextField(blank='True', null=True, verbose_name='Второе задание: задачи')),
                ('title_image', models.CharField(blank='True', max_length=256, verbose_name='Название картинки')),
                ('description_image', models.TextField(blank='True', verbose_name='Описание картинки')),
                ('image', models.ImageField(blank='True', null=True, upload_to='masterapp/image', verbose_name='картинка')),
                ('title_check_list', models.CharField(blank='True', max_length=256, verbose_name='название чек-листа')),
                ('description_check_list', models.TextField(blank='True', verbose_name='описание чек листа')),
                ('check_list', models.FileField(blank='True', null=True, upload_to='masterapp/check_list', verbose_name='чек лист')),
                ('title_audio_file', models.CharField(blank='True', max_length=256, verbose_name='Название медитации')),
                ('description_audio_file', models.TextField(blank='True', verbose_name='Описание медитации')),
                ('audio_file', models.FileField(blank='True', null=True, upload_to='masterapp/audio_file', verbose_name='медитация')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterapp.category')),
            ],
            options={
                'verbose_name': 'Модель курса',
                'verbose_name_plural': 'Модели курса',
            },
        ),
    ]
