# Generated by Django 3.2.9 on 2021-12-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0002_baswpageinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaswPageInfo',
            new_name='BasePageInfo',
        ),
    ]
