# Generated by Django 3.2.9 on 2021-12-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0003_rename_baswpageinfo_basepageinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catygory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='financecourse',
            old_name='catygory',
            new_name='category',
        ),
    ]
