# Generated by Django 3.2.9 on 2021-12-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0004_auto_20211205_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
