# Generated by Django 3.2.9 on 2021-12-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0005_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
