# Generated by Django 3.2.9 on 2021-12-08 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0006_remove_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceCourseLable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterapp.category')),
            ],
        ),
    ]
