# Generated by Django 3.2.9 on 2021-12-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0007_financecourselable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financecourselable',
            name='image',
        ),
    ]
