# Generated by Django 3.2.9 on 2021-12-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0008_remove_financecourselable_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financecourse',
            name='file',
            field=models.FileField(blank='True', upload_to=''),
        ),
        migrations.AlterField(
            model_name='financecourse',
            name='image',
            field=models.ImageField(blank='True', upload_to=''),
        ),
    ]
